version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: rural_postgres
    restart: always
    environment:
      POSTGRES_USER: rural_user
      POSTGRES_PASSWORD: rural_pass
      POSTGRES_DB: rural_db
    ports:
      - '5433:5432'
    volumes:
      - rural-postgres-data:/var/lib/postgresql/data

  api:
    build: .
    container_name: rural_api
    restart: always
    command: npm run start:dev
    ports:
      - '3001:3000'
    depends_on:
      - postgres
    environment:
      DB_HOST: rural_postgres
      DB_PORT: 5432
      DB_USER: rural_user
      DB_PASSWORD: rural_pass
      DB_NAME: rural_db

volumes:
  rural-postgres-data:
